// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcsvsjovogzosszlbnri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjc3Zzam92b2d6b3NzemxibnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTkwNTEsImV4cCI6MjA1NzUzNTA1MX0.46VlzzQLGhuvhct_xa1YhYDxh3shHH9alfK6ReBSVY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);